apiVersion: v1
kind: Secret
metadata:
  name: starttech-backend-secret
  namespace: starttech
type: Opaque
stringData:
  PORT: "8080"

  MONGO_URI: "mongodb+srv://isedeemmanuel26_db_user:gxS3ceOIiPNaEsz8@cluster0.6kasww3.mongodb.net/much_todo_db?appName=Cluster0"

  DB_NAME: "much_todo_db"

  JWT_SECRET_KEY: "StartTechSuperSecretJWTKey2026!"

  JWT_EXPIRATION_HOURS: "72"

  ENABLE_CACHE: "true"

  REDIS_ADDR: "starttech-redis.reru0a.0001.euw1.cache.amazonaws.com:6379"
  REDIS_PASSWORD: ""

  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"

  ALLOWED_ORIGINS: "*"

  COOKIE_DOMAINS: ""

  SECURE_COOKIE: "false"
